version: '3'
services:
  #####################################
  # APPLICATION SERVICE ENVIRONMENT
  #####################################
  app:
    build: .
    restart: always
    healthcheck:
      start_period: 60s
      timeout: 120s
      interval: 30s
      test: env | grep HOME
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - database
      - caching
    volumes:
      - .:/usr/share/app
      - /usr/share/app/node_modules
    networks:
      - node_networks
  ################################
  # DATABASE SERVICE ENVIRONMENT
  ################################
  database:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      start_period: 60s
      timeout: 120s
      interval: 30s
      test: env | grep HOME
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/mysql
    networks:
      - node_networks
  ################################
  # CACHING SERVICE ENVIRONMENT
  ################################
  caching:
    image: redis:7.0.3-alpine
    restart: always
    healthcheck:
      start_period: 60s
      timeout: 120s
      interval: 30s
      test: env | grep HOME
    ports:
      - 6379:6379
    volumes:
      - caching:/var/lib/redis
    networks:
      - node_networks
# #############################
# # VOLUME PERSISTENT DATA
# #############################
volumes:
  database:
  caching:
#############################
# NETWORKS SHARING GROUP
#############################
networks:
  node_networks: